# Generated by Django 5.2.8 on 2025-11-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_game_options_alter_listing_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('account', 'Аккаунт'), ('currency', 'Валюта'), ('service', 'Услуга'), ('other', 'Другое')], default='account', max_length=20, verbose_name='Категория'),
        ),
    ]
