# Generated by Django 5.2.8 on 2025-11-18 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_game_description_alter_game_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='server_number',
            field=models.IntegerField(default=1, help_text='Номер сервера от 1 до 50', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Номер сервера'),
        ),
    ]
