# Generated by Django 5.2.8 on 2025-11-19 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_server_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='server_number',
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: BR SERVER #1', max_length=100, verbose_name='Название сервера')),
                ('number', models.IntegerField(help_text='Уникальный номер для каждой игры', verbose_name='Номер сервера')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='listings.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
                'ordering': ['game', 'number'],
                'unique_together': {('game', 'number')},
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='server',
            field=models.ForeignKey(blank=True, help_text='Сервер игры', null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.server', verbose_name='Сервер'),
        ),
    ]
