# Generated by Django 5.2.8 on 2025-12-06 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена должна быть от 0.01 до 999999.99', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999999.99)], verbose_name='Цена'),
        ),
    ]
